### ISSUE TITLE
Error in VS2013 debug enviroment when call "pow" functin

### ISSUE THREAD

**Issue by ColaBH** [kasparsklavins/bigint#1]
Problem occurs only in debug version. But everything is ok in release. I can't figure out why.

Here is the detail information:

bigint a = 159753;
 cout << a.pow(6) << endl;
![prob](https://cloud.githubusercontent.com/assets/11325158/6501563/eea009f0-c354-11e4-8beb-53e73d8d05ca.png)

**Comment by kasparsklavins** [comment]
Should be resolved now. 6480a34fb61e5a6f6ba405e35ac9d5904da2aa77
