### ISSUE TITLE
Dead code found at line 78

### ISSUE THREAD

**Issue by TitanSnow** [kasparsklavins/bigint#10]
In file [bigint.cpp](https://github.com/kasparsklavins/bigint/blob/master/src/bigint.cpp) around line 73, I found this code:
```C++
Bigint &Bigint::operator+=(Bigint const &b)
{
    if (!b.positive) {
        return *this -= b;
    }
    if (!b.positive && positive) {
        positive = false;
    }
```
The first <code>if</code> make it returned when <code>!b.positive</code>, then the second <code>if</code> can't be true, right? So it should be dead code

**Comment by TitanSnow** [comment]
pull #11

**Comment by TitanSnow** [comment]
pull #11 closed. pull #12 instead

**Comment by kasparsklavins** [comment]
Closed since https://github.com/kasparsklavins/bigint/pull/12 has been merged.
