### ISSUE TITLE
Some question about division operation

### ISSUE THREAD

**Issue by TitanSnow** [kasparsklavins/bigint#13]
I found division operation has added in [#9e3967c](https://github.com/kasparsklavins/bigint/commit/9e3967c) but has removed in [#e093d1e](https://github.com/kasparsklavins/bigint/commit/e093d1e). Is it because of bugs or just for the commit [#7159412](https://github.com/kasparsklavins/bigint/commit/7159412)? If it's the second, why not get division operation back? I think division operation is also used widely

**Comment by kasparsklavins** [comment]
Because it wasnt working correctly and also the implementation was too slow.

**Comment by TitanSnow** [comment]
Thanks for answering. I think I'd like to implement one in free time
