### ISSUE TITLE
Bug with big number multiplication

### ISSUE THREAD

**Issue by MahmoudRizk** [kasparsklavins/bigint#15]
``` c++
#include<iostream>
#include<Bigint.h>
using namespace std;
using namespace Dodecahedron;
int main()
{
    Bigint a("4");
    Bigint b("100000000000000000000000000");
    Bigint c;
    c=a*b;
    cout<< c <<endl;
}
```
Given Output : 0
Correct Answer : 400000000000000000000000000

It fails when multiplying smaller number with large number, but not vice versa.

**Comment by kasparsklavins** [comment]
https://github.com/kasparsklavins/bigint/pull/16 Has been merged in.
